sonar.projectKey=kendo-tournament-frontend
sonar.organization=softwaremagico
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/coverage/**,**/environments/**
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info

