theme: jekyll-theme-slate

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

logo: blob/main/documents/logo.svg
title: Kendo Tournament Manager NG
description: Tool to efficiently manage all your kendo tournament data in one convenient location.
author:
  name: Jorge Hortelano
  email: softwaremagico@gmail.com

image:
  path: blob/main/frontend/src/assets/img/kote.svg