export enum ClubFormValidationFields {
  NAME_ERRORS = 'NAME_ERRORS',
  COUNTRY_ERRORS = 'COUNTRY_ERRORS',
  CITY_ERRORS = 'CITY_ERRORS',
  ADDRESS_ERRORS = 'ADDRESS_ERRORS',
  EMAIL_ERRORS = 'EMAIL_ERRORS',
  PHONE_ERRORS = 'PHONE_ERRORS',
  WEB_ERRORS = 'WEB_ERRORS',
}
