version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0'
    working_directory: ~/KendoTournamentManager/backend
    steps:
      - checkout:
          method: blobless
          path: ~/KendoTournamentManager
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=kendo-tournament-backend -DdeploySnapshot=true


  frontend-test:
    docker:
      - image: 'cimg/node:18.20.4-browsers'
    working_directory: ~/KendoTournamentManager/frontend
    steps:
      - checkout:
          method: blobless
          path: ~/KendoTournamentManager
      - run:
          name: Install Chromium
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: CHROME_BIN=/usr/bin/chromium-browser npm test -- --watch=false --browsers=ChromeHeadless

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - frontend-test
