version: 2.1

jobs:
  build:
    runs-on: ubuntu-latest
    docker:
      - image: 'cimg/openjdk:21.0'
    working_directory: ~/KendoTournamentManager/backend
    steps:
      - checkout:
          method: blobless
          path: ~/KendoTournamentManager
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=kendo-tournament-backend -DdeploySnapshot=true


  frontend-test:
    - uses: actions/checkout@v6 #Checkout Repo
    - uses: actions/setup-node@v6 #Setup Node
      with:
        node-version: '18'
    - name: Run Karma Tests
      run: |
        npm install
        npm run test        

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - frontend-test
