database.encryption.key=DATABASE_ENCRYPTION_KEY
jwt.secret=JWT_SECRET
jwt.ip.check=true
spring.kendo.datasource.platform=DATABASE_TYPE
spring.kendo.datasource.jdbc-url=jdbc:DATABASE_TYPE://kendo-tournament-database:DATABASE_PORT/DATABASE_NAME
spring.kendo.datasource.username=DATABASE_USER
spring.kendo.datasource.password=DATABASE_PASSWORD
server.domain=MACHINE_DOMAIN
