export enum AuthenticatedUserFormValidationFields {
  NAME_ERRORS = 'NAME_ERRORS',
  USERNAME_MANDATORY = 'USERNAME_MANDATORY',
  USERNAME_INVALID = 'USERNAME_INVALID',
  USERNAME_EXISTS = 'USERNAME_EXISTS',
  NAME_MANDATORY = 'NAME_MANDATORY',
  LASTNAME_MANDATORY = 'LASTNAME_MANDATORY',
  PASSWORD_MANDATORY = 'PASSWORD_MANDATORY',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
}
