name: Publish to Docker Hub

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [ "Create Release" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    name: Creating Docker Images
    runs-on: ubuntu-22.04
    # I need "packages: write" to access GHCR.
    # More about permissions here: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions: write-all
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v2

#      - name: Build docker-compose
#        run: docker buildx bake --file docker-compose.yml
#        with:
#          projectBaseDir: docker

      - name: Publish docker image
        uses: docker/bake-action@v6
        with:
          source: "{{defaultContext}}:docker"
          push: true
          set: |
            *.tags=user/app:latest
